// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8ZnjXqqJ0fSsiqSpRRjMFoBC95MUOgCU',
    appId: '1:1017308131693:web:6a170cb79728ab5be0aa64',
    messagingSenderId: '1017308131693',
    projectId: 'fx-crm',
    authDomain: 'fx-crm.firebaseapp.com',
    storageBucket: 'fx-crm.firebasestorage.app',
    measurementId: 'G-2JT7N1Q76G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDObnT9eA1qKiyjW1NXpUhyXGhSg74QX8A',
    appId: '1:1017308131693:android:6b8ae853bfa308d2e0aa64',
    messagingSenderId: '1017308131693',
    projectId: 'fx-crm',
    storageBucket: 'fx-crm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBT7QOcfre5jWYQe6_T-UuqWiyy8Kizug8',
    appId: '1:1017308131693:ios:7757e469bf19564ce0aa64',
    messagingSenderId: '1017308131693',
    projectId: 'fx-crm',
    storageBucket: 'fx-crm.firebasestorage.app',
    iosBundleId: 'com.app.fxCrm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBT7QOcfre5jWYQe6_T-UuqWiyy8Kizug8',
    appId: '1:1017308131693:ios:7757e469bf19564ce0aa64',
    messagingSenderId: '1017308131693',
    projectId: 'fx-crm',
    storageBucket: 'fx-crm.firebasestorage.app',
    iosBundleId: 'com.app.fxCrm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8ZnjXqqJ0fSsiqSpRRjMFoBC95MUOgCU',
    appId: '1:1017308131693:web:e797b54f72a29c19e0aa64',
    messagingSenderId: '1017308131693',
    projectId: 'fx-crm',
    authDomain: 'fx-crm.firebaseapp.com',
    storageBucket: 'fx-crm.firebasestorage.app',
    measurementId: 'G-9DTR6XCY73',
  );
}
